config/routes.rb
Rails.application.routes.draw do
  get 'subscribe/new'

  devise_for :users
  devise_scope :user do
    get 'signin', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end
  resources :subscribe
  delete '/cancel_plan' => 'subscribe#cancel_plan'
  resources :notes
  authenticated :user do
    root 'notes#index', as: "authenticated_root"
  end

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :user_subscribed!
  before_action :set_note, only: [:show, :edit, :update, :destroy]


  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    def user_subscribed!
      if current_user.subscribed == false
        redirect_to subscribe_index_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :content)
    end
end

app/controllers/subscribe_controller.rb
class SubscribeController < ApplicationController
  before_filter :authenticate_user!
  def index
    @stripe_list = Stripe::Plan.all
    @plans = @stripe_list[:data]
  end

  def new
  end

  def update
    token = params[:stripeToken]
    plan_id = params[:plan_id]
    plan = Stripe::Plan.retrieve(plan_id)

    customer = Stripe::Customer.create(
    :source => token,
    :plan => plan,
    :email => current_user.email
    )

    subscription = Stripe::Subscription.create(
    :customer => customer,
    :plan => plan
    )

    current_user.subscribed = true
    current_user.stripeid = customer.id
    current_user.subid = subscription.id
    current_user.planid = plan_id
    current_user.save

    redirect_to notes_path, :notice => "You're now subscribed"
  end

  def cancel_plan
    customer = Stripe::Customer.retrieve(current_user.stripeid)
    subscription = Stripe::Subscription.retrieve(current_user.subid)
    subscription.delete
    current_user.subscribed = false
    current_user.stripeid = nil
    current_user.subid = nil
    current_user.save
    redirect_to new_subscribe_path, :notice => "You're unsubscribed"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/subscribe_helper.rb
module SubscribeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stripetest</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  </head>

  <body>
    <nav class="nav">
        <% if user_signed_in? %>
          <% if current_user.subscribed == false %>
          <%= link_to 'Subscribe', subscribe_index_path %>
          <% else %>
          <%= link_to 'New Note', new_note_path %>
          <%= link_to 'My Notes', notes_path %>
          <%= link_to "Cancel my Subscription", cancel_plan_path, :data => { :confirm => "Are you sure?" }, :method => :delete %>
          <% end %>
        <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
        <% else %>
        <%= link_to 'Sign Up', signup_path %>
        <%= link_to 'Login', signin_path %>
        <% end %>
      </nav>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_for(note) do |f| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.title %></td>
        <td><%= note.content %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @note.content %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/subscribe/index.html.erb
<%= form_tag subscribe_path(1), :method => :put do %>
<% @plans.each do |plan| %>
  <div class="plan">
  <h1><%= plan[:name] %></h1>
  <p>£<%= plan[:amount]/100 %></p>
  <%= form_tag('/new', {method: :post, plan: plan}) do %>
    <input name="plan_id" type="hidden" value="<%= plan[:id] %>">
    </input>
  <% end %>
  <script
  src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="<%=
    Rails.configuration.stripe[:publishable_key] %>"
      data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
      data-label="Subscribe"
      data-currency="GBP"
      data-amount=(plan[:amount])
      data-locale="auto">
    </script>
  </div>
<% end %>
<% end %>

app/views/subscribe/new.html.erb
<%= form_tag subscribe_path(1), :method => :put do %>
  <article>
    <label class="amount">
      <span>Subscribe to Plan 1: £19.99</span>
    </label>
  </article>
<script
src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="<%=
  Rails.configuration.stripe[:publishable_key] %>"
    data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
    data-name="Demo Stripe"
    data-description="£19.99 per month"
    data-label="Subscribe"
    data-currency="GBP"
    data-amount="1999"
    data-locale="auto">
  </script> <p>
<%= link_to 'Back', notes_path %></p>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome To Stripe Test</h1>
<p>This is a stripe test.<br>I am learning how to set up a stripe subscript application using rails</p>